workspace:
  base: /go
  path: src/github.com/ysitd-cloud/app-controller

pipeline:
  env:
    image: ysitd/glide
    commands:
      - env
  dependency:
    image: ysitd/glide
    pull: true
    commands:
      - go get -v github.com/Masterminds/glide
      - cd $GOPATH/src/github.com/Masterminds/glide && git checkout a88a9a6c4eeaac084a90a0cd2ca8a148cbd3ff63 && go install && cd -
      - glide --home /go/.glide install -v
  unit:
    group: test
    image: ysitd/glide
    pull: true
    commands:
      - go test ./...
  build:
    group: test
    image: golang:1.9
    pull: true
    commands:
      - make all -j
