workspace:
  base: /go/src
  path: github.com/ysitd-cloud/app-controller

pipeline:
  env:
    image: ysitd/glide
    commands:
      - env
  dependency:
    image: ysitd/glide
    pull: true
    commands:
      - glide install -v
  unit:
    group: test
    image: ysitd/glide
    pull: true
    commands:
      - go test ./...
  build:
    group: test
    image: golang:1.9
    pull: true
    commands:
      - make all -j
