language: go
sudo: false

cache:
  directories:
    - $HOME/.glide

go:
  - 1.9
  - 1.9.1
  - 1.9.2

go_import_path: code.ysitd.cloud/component/deployer

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout a88a9a6c4eeaac084a90a0cd2ca8a148cbd3ff63 && go install && cd -
  - glide install -v

script:
  - go test ./...
  - make all
