MAJOR_VERSION = 1
MINOR_VERSION = 0
GIT_VERSION = 1.0.0
GIT_COMMIT = $(shell git log -1 --pretty=format:"%H")
BUILD_DATE = $(shell date +%Y-%m-%dT%H:%M:%S%z)
BUILD_VAR = -X version.gitCommit=$(GIT_COMMIT) -X version.buildDate=$(BUILD_DATE) -X version.major=$(MAJOR_VERSION) -X version.minor=$(MINOR_VERSION) -X version.gitVersion=$(GIT_VERSION)
BUILD_FLAG = -ldflags "$(BUILD_VAR)"

dist:
	mkdir dist

clean:
	rm -r dist

.PHONY: clean

all: dist/manager